In [1]:
# Setup and test cases 

%load_ext autoreload
%autoreload 2

import sys
sys.path.append("..")

from src.preprocessing import clean_label

examples = [
    "CB CARREFOUR MARKET SAINT-DENIS 28/10",
    "CARTE X6977 20/06 PLAYSTATION NETWORK",
    "PRLV SEPA DEEZER FR34ZZZ657871",
    "PRELEVEMENT SUEZ EAU REF FR50ZZZ983930",
    "FRAIS TENUE DE COMPTE 10/2026",
    "PAIEMENT CB 20/09 MONTREUIL ZETTLE *FOOD TRUCK",
    "CB NETFLIX.COM 12/03",
    "CB MICROSOFT*365 05/02",
    "CB G20 PARIS 15 03/04",
    "CB Café de la Gare 0412345 15/07",
]

for label in examples:
    print(f"{label:<48} -> {clean_label(label)}")

CB CARREFOUR MARKET SAINT-DENIS 28/10            -> CB CARREFOUR MARKET SAINT DENIS
CARTE X6977 20/06 PLAYSTATION NETWORK            -> CARTE PLAYSTATION NETWORK
PRLV SEPA DEEZER FR34ZZZ657871                   -> PRLV SEPA DEEZER
PRELEVEMENT SUEZ EAU REF FR50ZZZ983930           -> PRELEVEMENT SUEZ EAU REF
FRAIS TENUE DE COMPTE 10/2026                    -> FRAIS TENUE DE COMPTE
PAIEMENT CB 20/09 MONTREUIL ZETTLE *FOOD TRUCK   -> PAIEMENT CB MONTREUIL ZETTLE FOOD TRUCK
CB NETFLIX.COM 12/03                             -> CB NETFLIX COM
CB MICROSOFT*365 05/02                           -> CB MICROSOFT 365
CB G20 PARIS 15 03/04                            -> CB G20 PARIS 15
CB Café de la Gare 0412345 15/07                 -> CB CAFE DE LA GARE

In [2]:
# Apply the cleaning 

import pandas as pd

df = pd.read_csv("../data/raw/transactions.csv")
df["clean_label"] = df["label"].apply(clean_label)

df[["label", "clean_label", "category"]].sample(10, random_state=42)

,label,clean_label,category
3135,CB MEDIPOLE 21/10 CARTE X4721,CB MEDIPOLE CARTE,Health
2191,CB EBAY 08/02,CB EBAY,Shopping
1295,CB SAEMES 26/01,CB SAEMES,Transport
2902,PAIEMENT CB 01/05 TOULOUSE MUTUELLE MGEN,PAIEMENT CB TOULOUSE MUTUELLE MGEN,Health
168,PAIEMENT PAR CARTE NETTO 23/05,PAIEMENT PAR CARTE NETTO,Groceries
1128,PAIEMENT PAR CARTE ALLIANCE CARBURANTS 18/01,PAIEMENT PAR CARTE ALLIANCE CARBURANTS,Transport
4530,RETRAIT DAB 22/09 LILLE,RETRAIT DAB LILLE,Cash Withdrawal
4281,RETRAIT DAB 24/06 NICE,RETRAIT DAB NICE,Cash Withdrawal
4176,RETRAIT DAB 10/10 GRENOBLE,RETRAIT DAB GRENOBLE,Cash Withdrawal
1020,CB APRR 01/03,CB APRR,Transport

In [3]:
# How much variety is left after cleaning ? 

print(f"Rows: {len(df)}")
print(f"Distinct clean labels: {df['clean_label'].nunique()}")

conflicts = df.groupby("clean_label")["category"].nunique()
print(f"Clean labels assigned to more than one category: {(conflicts > 1).sum()}\n")

df.groupby("category")["clean_label"].nunique().sort_values()

Rows: 4960
Distinct clean labels: 2822
Clean labels assigned to more than one category: 0

category
Bank Fees               30
Transfers              167
Income                 174
Housing & Utilities    189
Cash Withdrawal        200
Subscriptions          222
Leisure & Travel       238
Transport              249
Health                 272
Groceries              343
Shopping               368
Restaurants            370
Name: clean_label, dtype: int64

In [4]:
# Save the cleaned dataset

columns = ["label", "clean_label", "category", "merchant", "payment_type"]
df[columns].to_csv("../data/processed/transactions_clean.csv", index=False)
print(f"Saved {len(df)} rows to data/processed/transactions_clean.csv")

Saved 4960 rows to data/processed/transactions_clean.csv

In [5]:
# Load and inspect the realistic set 

realistic = pd.read_csv("../data/test_realistic.csv")
realistic["clean_label"] = realistic["label"].apply(clean_label)

train = pd.read_csv("../data/processed/transactions_clean.csv")

unknown = set(realistic["category"]) - set(train["category"])
seen = realistic["clean_label"].isin(train["clean_label"])

print(f"{len(realistic)} realistic labels")
print(f"Unknown categories (typos): {unknown if unknown else 'none'}")
print(f"Clean labels already present in the synthetic data: {seen.sum()}\n")

realistic[["label", "clean_label", "category"]]

60 realistic labels
Unknown categories (typos): none
Clean labels already present in the synthetic data: 2

,label,clean_label,category
0,CARTE X4512 14/03 BIOCBON PARIS 11,CARTE BIOCBON PARIS 11,Groceries
1,CB INTERMARCHE SUPER 08/04/26,CB INTERMARCHE SUPER,Groceries
2,FACTURE CARTE DU 120326 AUCHAN SUPERMARCHE CAR...,FACTURE CARTE DU AUCHAN SUPERMARCHE CARTE 4974...,Groceries
3,PAIEMENT CB 0904 ROUEN MONOP,PAIEMENT CB ROUEN MONOP,Groceries
4,CB BOUCHERIE DU MARCHE 21/03,CB BOUCHERIE DU MARCHE,Groceries
5,CB BIG FERNAND 15/03,CB BIG FERNAND,Restaurants
6,FACTURE CARTE DU 180326 PRET A MANGER CARTE 49...,FACTURE CARTE DU PRET A MANGER CARTE 4974XXXXX...,Restaurants
7,CB SUMUP *LA TRATTORIA 22/03,CB SUMUP LA TRATTORIA,Restaurants
8,CB UBER *EATS HELP.UBER.COM 03/04,CB UBER EATS HELP UBER COM,Restaurants
9,PAIEMENT CB 2803 LYON BRASSERIE GEORGES,PAIEMENT CB LYON BRASSERIE GEORGES,Restaurants
10,CB SNCF VOYAGEURS 07/03,CB SNCF VOYAGEURS,Transport
11,CB STATION ESSO EXPRESS 14/03,CB STATION ESSO EXPRESS,Transport
12,PRLV SEPA BIP&GO ECH/050326,PRLV SEPA BIP GO ECH,Transport
13,CB FREENOW 19/03,CB FREENOW,Transport
14,FACTURE CARTE DU 250326 Q-PARK FRANCE CARTE 49...,FACTURE CARTE DU Q PARK FRANCE CARTE 4974XXXXX...,Transport
15,PRLV SEPA NETFLIX INTERNATIONAL B.V. ECH/150326,PRLV SEPA NETFLIX INTERNATIONAL B V ECH,Subscriptions
16,CB SPOTIFY P2F3A8C21 10/03,CB SPOTIFY P2F3A8C21,Subscriptions
17,CB CLAUDE.AI SUBSCRIPTION 01/04,CB CLAUDE AI SUBSCRIPTION,Subscriptions
18,PRLV SEPA LE PARISIEN ABONNEMENT,PRLV SEPA LE PARISIEN ABONNEMENT,Subscriptions
19,CB DASHLANE 12/03,CB DASHLANE,Subscriptions
20,CB ZARA HOME 16/03,CB ZARA HOME,Shopping
21,FACTURE CARTE DU 200326 BOULANGER LA DEFENSE C...,FACTURE CARTE DU BOULANGER LA DEFENSE CARTE 49...,Shopping
22,CB AMZN MKTP FR 23/03,CB AMZN MKTP FR,Shopping
23,CB TEMU.COM 27/03,CB TEMU COM,Shopping
24,PAIEMENT CB 3003 LILLE CELIO,PAIEMENT CB LILLE CELIO,Shopping
25,PRLV SEPA EDF CLIENTS PARTICULIERS ECH/100326,PRLV SEPA EDF CLIENTS PARTICULIERS ECH,Housing & Utilities
26,PRLV SEPA FREE MOBILE 0612345678,PRLV SEPA FREE MOBILE,Housing & Utilities
27,VIR SEPA LOYER MARS SCI DU PARC,VIR SEPA LOYER MARS SCI DU PARC,Housing & Utilities
28,PRLV SEPA LEOCARE ASSURANCE,PRLV SEPA LEOCARE ASSURANCE,Housing & Utilities
29,PRLV SEPA TOTALENERGIES ELEC ET GAZ,PRLV SEPA TOTALENERGIES ELEC ET GAZ,Housing & Utilities
30,CB PHARMACIE DES ARCADES 11/03,CB PHARMACIE DES ARCADES,Health
31,PRLV SEPA ALAN SA,PRLV SEPA ALAN SA,Health
32,CB DOCTOLIB*DR MARTIN 04/03,CB DOCTOLIB DR MARTIN,Health
33,FACTURE CARTE DU 170326 OPTIC 2000 CARTE 4974X...,FACTURE CARTE DU OPTIC CARTE 4974XXXXXXXX1234,Health
34,CB CENTRE MEDICAL GARE DE LYON 24/03,CB CENTRE MEDICAL GARE DE LYON,Health
35,CB CINEMA LE BALZAC 08/03,CB CINEMA LE BALZAC,Leisure & Travel
36,CB AIRBNB * HMXYZ12 12/03,CB AIRBNB HMXYZ12,Leisure & Travel
37,PRLV SEPA L ORANGE BLEUE,PRLV SEPA L ORANGE BLEUE,Leisure & Travel
38,CB SEETICKETS 05/04,CB SEETICKETS,Leisure & Travel
39,CB KINEPOLIS 30/03,CB KINEPOLIS,Leisure & Travel
40,VIR SEPA RECU /DE CAPGEMINI TECHNOLOGY SERVICE...,VIR SEPA RECU DE CAPGEMINI TECHNOLOGY SERVICES...,Income
41,VIR CAF DE SEINE SAINT DENIS PRESTATIONS,VIR CAF DE SEINE SAINT DENIS PRESTATIONS,Income
42,VIR SEPA RECU DE CPAM DE PARIS REMBOURSEMENT S...,VIR SEPA RECU DE CPAM DE PARIS REMBOURSEMENT S...,Income
43,VIR FRANCE TRAVAIL ARE 03/2026,VIR FRANCE TRAVAIL ARE,Income
44,VIR SEPA RECU DE DGFIP REMBOURSEMENT IR,VIR SEPA RECU DE DGFIP REMBOURSEMENT IR,Income
45,VIR INST VERS M. DUPONT THOMAS,VIR INST VERS M DUPONT THOMAS,Transfers
46,VIR SEPA RECU DE MME MARTIN CLAIRE REMBOURSEME...,VIR SEPA RECU DE MME MARTIN CLAIRE REMBOURSEME...,Transfers
47,VIREMENT VERS LIVRET A,VIREMENT VERS LIVRET A,Transfers
48,VIREMENT PERMANENT VERS LIVRET JEUNE,VIREMENT PERMANENT VERS LIVRET JEUNE,Transfers
49,VIR SEPA RECU DE BERNARD NICOLAS,VIR SEPA RECU DE BERNARD NICOLAS,Transfers
50,RETRAIT DAB 14/03 CREDIT AGRICOLE PARIS 15,RETRAIT DAB CREDIT AGRICOLE PARIS 15,Cash Withdrawal
51,RET DAB 0503 LYON 2 CARTE X4512,RET DAB LYON 2 CARTE,Cash Withdrawal
52,RETRAIT DAB LA BANQUE POSTALE GARE DU NORD 22/03,RETRAIT DAB LA BANQUE POSTALE GARE DU NORD,Cash Withdrawal
53,RETRAIT DAB 12/04 BARCELONA ES EUR 100.00,RETRAIT DAB BARCELONA ES EUR 100 00,Cash Withdrawal
54,RETRAIT ESPECES GUICHET 18/03,RETRAIT ESPECES GUICHET,Cash Withdrawal
55,COMMISSION D INTERVENTION 1 OPERATION 14/03,COMMISSION D INTERVENTION 1 OPERATION,Bank Fees
56,FRAIS PAIEMENT HORS ZONE EURO 12/04 BARCELONA,FRAIS PAIEMENT HORS ZONE EURO BARCELONA,Bank Fees
57,COTISATION CARTE VISA CLASSIC 2026,COTISATION CARTE VISA CLASSIC,Bank Fees
58,COTIS OFFRE ESSENTIELLE ECH 05/03,COTIS OFFRE ESSENTIELLE ECH,Bank Fees
59,INTERETS DEBITEURS ARRETE AU 31/03/2026,INTERETS DEBITEURS ARRETE AU,Bank Fees